// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtUicDCjPQwtGQdMWaGEJapV886Q2CTeU',
    appId: '1:466771791719:web:1a2af0d87527d25ba7e9c2',
    messagingSenderId: '466771791719',
    projectId: 'test-fbbe6',
    authDomain: 'test-fbbe6.firebaseapp.com',
    storageBucket: 'test-fbbe6.appspot.com',
    measurementId: 'G-B1XRMNB8HS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAROtNGstffcXb_GfIzCqmhck-JZ-ZxTGs',
    appId: '1:466771791719:android:667b83bf6617c44fa7e9c2',
    messagingSenderId: '466771791719',
    projectId: 'test-fbbe6',
    storageBucket: 'test-fbbe6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUAPbeka3avv1_gzAvQagt5I3Oz5EMr7o',
    appId: '1:466771791719:ios:b8277333d5cfc994a7e9c2',
    messagingSenderId: '466771791719',
    projectId: 'test-fbbe6',
    storageBucket: 'test-fbbe6.appspot.com',
    iosClientId: '466771791719-r8b0u4ttmi74u1ke7q8ab4ik3brhb5hm.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedexDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUAPbeka3avv1_gzAvQagt5I3Oz5EMr7o',
    appId: '1:466771791719:ios:b8277333d5cfc994a7e9c2',
    messagingSenderId: '466771791719',
    projectId: 'test-fbbe6',
    storageBucket: 'test-fbbe6.appspot.com',
    iosClientId: '466771791719-r8b0u4ttmi74u1ke7q8ab4ik3brhb5hm.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedexDemo',
  );
}
